version: '3'

volumes:
  db_vol:
  static_vol:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

services:
  db:
    image: mysql:8.0.25
    volumes:
      - db_vol:/var/lib/mysql:rw
      - ./compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./compose/mysql/init:/docker-entrypoint-initdb.d
    env_file:
      - compose/mysql/.env
    networks:
      - db_network
    ports:
      - "3306:3306"
    restart: always

  nginx:
    image: nginx:1.20.0
    volumes:
      - static_vol:/usr/share/nginx/html/static
      - ./compose/nginx/blogsite.conf:/etc/nginx/conf.d/blogsite.conf
      - ./compose/nginx/log:/var/log/nginx
      - ./compose/nginx/ssl:/usr/share/nginx/ssl
    networks:
      - nginx_network
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    restart: always
    command: ["nginx", "-g", "daemon off;"]

  web:
    build: ./blogsite
    container_name: blogsite
    volumes:
      - static_vol:/var/www/html/blogsite/static
      - ./blogsite:/var/www/html/blogsite
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db
    expose:
      - "8000"
    restart: always
    tty: true
    stdin_open: true
