# Generated by Django 3.2.3 on 2021-06-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=1, verbose_name='访问者'),
        ),
    ]
